# permissions for end users to edit redisoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisoperator-editor-role
rules:
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - redisoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - redisoperators/status
  verbs:
  - get
