---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - redisoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - redisoperators/finalizers
  verbs:
  - update
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - redisoperators/status
  verbs:
  - get
  - patch
  - update
