apiVersion: api.core.matanmagen.io/v1alpha1
kind: RedisOperator
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisoperator-sample
  namespace: oshri-ns
spec:
  redisversion: "6.0.10"  # replace with the desired Redis version
  exporterVersion: "latest"  # replace with the desired Exporter version
  teamName: "team-matan"  # replace with your team name