name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    uses: digitalidf/digitalidf-actions/.github/workflows/build-and-push-image.yaml@main
    with:
      image: redis-operator