name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    uses: digitalidf/digitalidf-actions/.github/workflows/build-and-push-image.yaml@v1.2.2
    with:
      image: redis-operator
      enable_latest_tag: true